### ISSUE TITLE
enhancement request

### ISSUE THREAD

**Issue by ameel** [ELynx/pokemon-go-xposed-mitm#10]
Is it possible at all to obtain pokemons' IV on encounter (ie while catching)?

Thanks for your good work!

**Comment by krokofant** [comment]
If you're wondering if it's techincally possible then yes. Another Xposed module features this functionality and exposed the data via a notification.

If it's just the end functionality you're after then it might suit you.
http://repo.xposed.info/module/de.chuparch0pper.android.xposed.pogoiv

**Comment by ELynx** [comment]
@krokofant Exactly my answer, thank you!

There are specialized modules, dedicated to IVs, one mentioned above is really good by doing that you ask.
Two reasons this will not appear inside current module now:
1) Main focus now is on adding JRuby/Ruby, not on individual hacks
2) Don't want to steal someone's else ideas

After scripting is implemented - this is a good hack to do.
