### ISSUE TITLE
Pokemon Go Xposed Mitm has stopped working

### ISSUE THREAD

**Issue by grizzlyjack** [ELynx/pokemon-go-xposed-mitm#13]
Nexus 5X with Android 6.0.1 (rooted) xposed framework installed and pokemon xposed installed. After upgrading to the 1.3.2 version the app launched once and now crashes every time i try to launch. Note: Pokemon nicknames have been changed to show IV stats but Lure time not working/cant access the Mitm app

**Comment by ELynx** [comment]
App require permissions to write and read files. Do you have them turned off?

With file explorer of your choice, navigate to /storage/emulated/0/Pokemon folder. Turn on viewing of hidden files. Do you have file .pogoxmitm-settings?

**Comment by grizzlyjack** [comment]
I do have this file. I found that permissions were not enabled for the app even though initially i enabled them when i first downloaded. This has fixed the problem, thanks!

**Comment by ELynx** [comment]
Great! Thank you for your feedback!
I will add this to instructions for module, just in case.

**Comment by Vahalaru** [comment]
i have same problem and found file in folder it has rw permissions but still crashes ps. what does the grade letter stand for in nickname and the last number in nickname stand for

**Comment by Vahalaru** [comment]
well the /data/app/  folder has rw r the /storage/emulated/blah/blah/pokemon file has rwrw is that the problem?

**Comment by Vahalaru** [comment]
figured it out. i am on marshmellow and had to go to settings app permissions then allow storage

**Comment by ELynx** [comment]
@Vahalaru Thanks for feedback!
I will use that wording, storage permission, I have android 4.4.2 myself, and non-english too. So I had no idea how this is called.

For letter - Grade. A means 100 to 91, B 90 to 81 percent and so on. So when you turn on sorting A-Z you see perfects and near-perfects first, good, then the rest.

Last number is a level, or how I see level. For new Pokemon it is derived from CP multiplier, and leter as you power them up it is increased by 0.5 for each power up.
