### ISSUE TITLE
Dump input and output stream

### ISSUE THREAD

**Issue by hurie** [ELynx/pokemon-go-xposed-mitm#14]
It nice to be able to dump input and output stream to a file or may be to sqlite database. 

There is lot of use of dumps like validate PROTO structure and other.

**Comment by ELynx** [comment]
You are welcome to code a hack for this. While I see this useful myself, I now focus on Ruby/JRuby and don't plan for new features hack-vise.
This will not take a big effort, stream classes used in Mitm already do read-write on other streams.

**Comment by ELynx** [comment]
No new info, closing
