### ISSUE TITLE
Enhancement request

### ISSUE THREAD

**Issue by riththerift** [ELynx/pokemon-go-xposed-mitm#15]
Hi,

Would you be able to show the Pokémon's name alongside the IV stuff? I am also using the PoGoIV module but the information displayed is not as nice as yours and PoGoIV doesn't display the lure time.

PoGoIV module link is here: http://repo.xposed.info/module/de.chuparch0pper.android.xposed.pogoiv

**Comment by ELynx** [comment]
@xstahsie @chuparch0pper
Hi,
In future, when JRuby/Ruby will be added, why not.
Now main focus of development is adding scripting language. Current hacks are added as proofs of concept, and as tests. This module is not (only) an IV checker.
If you like format this module uses - feel free to suggest it to author of said module, I don't mind it being used given I get credit.
