### ISSUE TITLE
Asking for new features

### ISSUE THREAD

**Issue by alexkruegger** [ELynx/pokemon-go-xposed-mitm#16]
Just for information - do you plan to add functionality like in these modules:

http://repo.xposed.info/module/de.elfinlazz.android.xposed.pokemongo
or
http://repo.xposed.info/module/info.xposed.mirosz.pogoivy

with customizable IV/LEV/e t.c. format, and

http://repo.xposed.info/module/de.chuparch0pper.android.xposed.pogoiv

with ability to show poko IV/LEV before catching ?

Right now we have to install all these modules to make playing more comfortable. If all of these functions will be in one module - it will be more useful.

Just question )

**Comment by ELynx** [comment]
Hi,
In future, when JRuby/Ruby will be added, why not.
Now main focus of development is adding scripting language. Current hacks are added as proofs of concept, and as tests. This module is not (only) an IV checker.
Feel free to suggest features from here to other authors, I don't mind them being used if contributors of this module are given proper credit.
Or convince them to contribute their code to this module xD
