### ISSUE TITLE
First letter explanation please?

### ISSUE THREAD

**Issue by jayceepooze** [ELynx/pokemon-go-xposed-mitm#2]
Hi,

The nicknames that show up have a letter, % (I'm guessing perfection), then Attack, Defense, Stamina.

What is that first letter supposed to indicate?

**Comment by krokofant** [comment]
The code states: _For A-Z sorting to see best ones at glance_

```
   // For A-Z sorting to see best ones at glance
        String prefix;
        if (total > 89)
            prefix = "A";
        else if (total > 79)
            prefix = "B";
        else if (total > 69)
            prefix = "C";
        else if (total > 59)
            prefix = "D";
        else if (total > 49)
            prefix = "E";
        else if (total > 39)
            prefix = "F";
        else if (total > 29)
            prefix = "G";
        else if (total > 19)
            prefix = "H";
        else if (total > 9)
            prefix = "I";
        else
            prefix = "J";
```

Where total is defined as: `int total = (atk + def + sta) * 100 / 45;`

So it seems to be IV.

https://github.com/ELynx/pokemon-go-xposed-mitm/blob/master/app/src/main/java/com/elynx/pogoxmitm/IvHack.java#L59

**Comment by ELynx** [comment]
Yes, that's correct. This is same as IVs in percent, just represented as letter. A means best, B worse than A, C worse than B and so on.
This is for sortingh pokemons, if you turn on A-Z sorting all with IVs from 90 to 100 will go first, then from 80 to 90.
