### ISSUE TITLE
PoGo crashes when enabling the mobule

### ISSUE THREAD

**Issue by mazzod** [ELynx/pokemon-go-xposed-mitm#21]
Hi all, 

As the title say, on my shield tablet running android 6.0,  if I enable the module and I try to open the game, it crash. I have enabled the storage permission in the options

**Comment by ELynx** [comment]
OK, this asks for log files.
Please install [this](https://play.google.com/store/apps/details?id=com.tortel.syslog&hl=ru) app, and give it root access for some time.
In app, leave Main Log check box on, others off.
Then start PoGo, wait until it crashes, and go back to app.
In app, press take log, and save them where you can access them from PC, e.g. Google drive.
From there, find logcat.log and see that it have something like

```
09-06 13:03:56.702 E/dalvikvm(28409): >>>>> com.nianticlabs.pokemongo [ userId:0 | appId:10215 ]
09-06 13:03:56.772 I/[PoGo MITM](28409): Init file object with path: /storage/emulated/0/Pokemon/.pogoxmitm-settings
09-06 13:03:56.772 I/[PoGo MITM](28409): Loading settings file
09-06 13:03:56.782 I/[PoGo MITM](28409): Settings
09-06 13:03:56.782 I/[PoGo MITM](28409): IvHack true
09-06 13:03:56.782 I/[PoGo MITM](28409): FortHack true
09-06 13:03:56.782 I/[PoGo MITM](28409): ExportHack true
09-06 13:03:56.782 I/Xposed  (28409): Injecting into PoGo
```

or at least `com.nianticlabs.pokemongo`

If it does, provide full log capture.

**Comment by mazzod** [comment]
Ok let me do what you asked, I'll post here the log. Thks! And thks to have correct the title :)

**Comment by mazzod** [comment]
Here the log: [redacted]
Let me know if I made all correctly

**Comment by ELynx** [comment]
@mazzod Got your log files, will check.
I redacted your comment, there were some Google Auth tokens there.

**Comment by ELynx** [comment]
@mazzod How many modules fo you have enabled?
Looking at 1st package of the app:

```
java.lang.NullPointerException at info.xposed.mirosz.pogoivy
java.lang.NullPointerException at de.chuparch0pper.android.xposed.pogoiv
```

OK, they get null pointers because this module hacks in and fails.

```
java.lang.NullPointerException at com.elynx.pogoxmitm.Options.getIvHack
```

Looks like PoGo cannot read settings file

```
09-06 12:33:48.369 I/[PoGo MITM](12492): Init file object with path: /storage/emulated/0/Pokemon/.pogoxmitm-settings
09-06 12:33:48.370 I/[PoGo MITM](12492): Loading settings file
09-06 12:33:48.372 I/[PoGo MITM](12492): java.io.IOException: File '/storage/emulated/0/Pokemon/.pogoxmitm-settings' cannot be read
```

So, can you:
- Check if PoGo have Storage Permissions;
- Check again if module have Storage Permissions. I had a report that they were turned off after being initially granted;
- Open module, and turn on all check boxes. Then close completely, and open again. Do check boxes remain on;
- With file explorer of your choice, navigate to `/storage/emulated/0/Pokemon` and see if `.pogoxmitm-settings` file is there. Make sure to turn on "show hidden files" or similar, dot-files are hidden by defult.

**Comment by ELynx** [comment]
Also, delete file you uploaded, and check download counter. Even if it is not visible here, some parts of Github still show the link.

**Comment by mazzod** [comment]
Thks to point me in the right way, and thks for have deleted the comments. I have also delete my uploaded file and changed my Google password.
For the problem of the module I will check when I go back home! Cheers

**Comment by mazzod** [comment]
Thks @ELynx you point me in the right way, my PoGo app didn't have the storage permission, now all works fine. FYI with your module I have enabled 2 more modules and all together works perfectly

**Comment by mazzod** [comment]
You can close this issue. I think that you need to write in the main page that PoGo need storage permission so no one open again an issue for this problem and you can focus to other things :)

**Comment by ELynx** [comment]
@mazzod Great, glad to help!
I slowly fill readme with FAQ, will add this one too :)
