### ISSUE TITLE
QUESTION: With the default settings, what do the letters stand for?

### ISSUE THREAD

**Issue by xomikronx** [ELynx/pokemon-go-xposed-mitm#22]
Hi,

This is more of a question than an issue.  Didn't see a chat/support channel, so I thought I ask here.

With the default pokemon, you see [letter] -[IV] - [atk - [def] - [sta] - [level].

For example, D 66% 2-15-13 14.0

How are you determining the first letter or is this just randomly generated?

I'm using version 1.3.2.

Thanks,

**Comment by ELynx** [comment]
@xomikronx This is Grade. A is for 100-91, B is for 90-81 and so on. Sort pokemon A-Z and you will see best first.

Same asked in #2. Added info to readme/module description. Commit https://github.com/ELynx/pokemon-go-xposed-mitm/commit/6ad67a9810f86ce36cf3c61bf1cddc4cb09027a2
