### ISSUE TITLE
What min version to play pokemon with xposed

### ISSUE THREAD

**Issue by qhairrul** [ELynx/pokemon-go-xposed-mitm#26]
Hi Elynx..i just tired try any solution latest version to play pokemon go with xposed.not work..i install magisk on my galaxy s4 lolipop..its work..when i install xposed..it won't load..tired to disable xposed ..still  loading. i have lot stufg module very important to me.

**Comment by ELynx** [comment]
@qhairrul Hi,
I am not the author of latest release, @FreedomMercenary is. Try asking him, may be he can help.

**Comment by FreedomMercenary** [comment]
@qhairrul As of now, here's the current status of working methods with Root & Xposed installed:

Rooted with Magisk
- **Must have already switched off Xposed** and restarted (toggling is not immediate with Xposed, must reboot in-between always)
- Must have root toggled Off to start Pokemon

Rooted with SuperSU + suhide (Currently best option)
- Best option is [suhide](http://forum.xda-developers.com/apps/supersu/suhide-t3450396) which requires you are rooted with the specific version of SuperSU in Systemless mode (must use echo command to force systemless install) and then flash suhide
- Xposed may be left on and used while launching Pokemon, as well as root which will always be on
- Causes issues with some apps like Snapchat - you have to add them to suhide's blocklist
- Not supported on all phones, requires that it can patch the boot image, drains battery like hell and leads to at least slight performance degradation on the phone or worse

The only current working way to play on a phone with Xposed on is suhide.  If you are having issues, the first step is to evaluate which situation above you are in and make sure things are working (Xposed can't be on with Magisk based root / PHH).  If they aren't, first step is to check Xposed logs in the app and post them here.  Next, remove Xposed (framework only is fine) and try to get Pokemon working.  After that, you can re-flash the framework and make sure everything's configured correctly so it's in a state that's expected to work.
