### ISSUE TITLE
Problem with multiple Pogo Account

### ISSUE THREAD

**Issue by Webfred34** [ELynx/pokemon-go-xposed-mitm#27]
Hello and thank you very much for this useful module.

I have 2 Pogo accounts that i use with the same device.
I switch from one account to other by doing that :
1 -  stop Pogo application
2 - clear data and cache of Pogo in Application Manager
3 - restart pogo
After that, I can login with my second account by selecting it in the list of google account

Problem is Pogo crash every time I do step 3 if the module is loaded.
(message "Pogo has stopped")
I restart again Pogo and it's OK I can launch the game with my other account.

If I disable module, I have not this behavior so I am sure it is the cause.
I specify this problem is present since the beginning and not since the last 1.3.2 version.

It's not a major problem because that works after the 1st crash application but  I will be happy if it can be fixed because that will take less time to switch from an account to another.  ;-)
(and also because  perhaps some crash log could be generated and sent to pogo server when it crash ...)

Best regards and thank you again for your work.

**Comment by riththerift** [comment]
Why are you not using this app called Multiple Accounts to switch accounts? That's what I'm using and it works great. You could also use this app called Parallel which allows multiple instances of Pokémon Go to run on your phone.

**Comment by Webfred34** [comment]
Hi,
thank you for your feedback.
I tried the app Multiple Account you said, and you are right that's work perfect.
Now I can quickly switch from a Pogo account to another without have a Pogo crash on startup and all my Xposed modules works fine for each account.
thank you so much, that solve my problem :-)

**Comment by riththerift** [comment]
Sure thing, man.
