### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Yureika** [ELynx/pokemon-go-xposed-mitm#4]
It stop working while i try to open "Grimer"
Using Acer liquid z520

**Comment by ELynx** [comment]
Can you give me some background? By opening you mean opening detailed information for pokemon?
Before opening, how does 'mon nickname look like? Is it changed, or not?
If it is, can you report what it shows?
Also, some users report that Grimer's model cause their game to crash.
[Reddit 1](https://www.reddit.com/r/pokemongo/comments/4rzpjg/grimers_model_makes_my_game_crash)
[Reddit 2](https://www.reddit.com/r/pokemongo/comments/4sy8jx/grimer_game_freezecrash/)
So, report more details please.

**Comment by Yureika** [comment]
Here's the screenshot.
The names is changing (it woks great)
But when i want to see detailed about "Grimer" it's stuck at that screen.
And there's a warning pop out say's "Pokémon Go not responding"

**Comment by ELynx** [comment]
Can't see your screenshot.
Since the name is changing, then module is doing it's work.
Can you try to disable the module in XPosed, reboot the phone, and try to see info on Grimer. Is it still crashing?

**Comment by ELynx** [comment]
No new information. Probably Grimer model bug. Closing.
