### ISSUE TITLE
Dynamic settings for module

### ISSUE THREAD

**Issue by ELynx** [ELynx/pokemon-go-xposed-mitm#5]
Use FileObserver singleton
Code-side - apply settings without polling
User-side - allow settings to take effect without restarting PoGo
See #3 for initial discussion

**Comment by krokofant** [comment]
Should the settings be used to store the different Ruby scripts? If not - how would that be solved?

**Comment by ELynx** [comment]
I think this can be done as simple "scripts on" list, as it works now in non-ruby version.
During UI load, list all available scripts, and let user check ones that should be actually used.
And then during XPosed module load read list of activated scripts, read script content, and load them.

On next step _may be_ store script settings, if any, but I am not sure how a script may tell Java that it has a setting and so on.
So far even making JRuby print Hello world is a task in itself...

**Comment by griest024** [comment]
So it sounds like what we needs is a list of hacks that are to be implemented and then write a script for each one.

@Elynx did you get the ruby test script to run at all?

**Comment by ELynx** [comment]
@griest024 So far I am stuck in configuring Ruboto<->JRuby, but I am slowly going, from total exceptions to at least ones I can sort of understand. Progress is slow, tho.
I think for initial switch to Ruby only already existing hacks should be made. IVs and Lure time are pretty simple, since they are independent of any global states, are server->client only, and so on.
csv hack will be a good starting point for defining what is needed beside basics, since it requires a file write, a toast notif, and so on.

**Comment by griest024** [comment]
@ELynx where can we keep a dialog going? I don't want to pollute these issues with off topic discussion. Do you want to get a Discord channel going?

**Comment by ELynx** [comment]
@griest024 I opened a new issue #11 with latest struggles with JRuby and Ruboto. Looks like ice is broken, finally. Now we just need to place test rb file so that it is placed properly in android.
why not telegram? it is more generic.

**Comment by ELynx** [comment]
Implemented!
