### ISSUE TITLE
FC when internet connection lost

### ISSUE THREAD

**Issue by eslym** [ELynx/pokemon-go-xposed-mitm#7]
Just like the log, fatal error.
`08-27 11:46:39.694: E/AndroidRuntime(7277): FATAL EXCEPTION: pool-2-thread-1
08-27 11:46:39.694: E/AndroidRuntime(7277): Process: com.nianticlabs.pokemongo, PID: 7277
08-27 11:46:39.694: E/AndroidRuntime(7277): java.lang.Error: FATAL EXCEPTION [pool-2-thread-1]
08-27 11:46:39.694: E/AndroidRuntime(7277): Unity version     : 5.3.5f1
08-27 11:46:39.694: E/AndroidRuntime(7277): Device model      : OPPO F1f
08-27 11:46:39.694: E/AndroidRuntime(7277): Device fingerprint: OPPO/F1f/F1f:5.1.1/LMY47V/1446204931:user/release-keys
08-27 11:46:39.694: E/AndroidRuntime(7277): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.OutputStream.write(byte[], int, int)' on a null object reference
08-27 11:46:39.694: E/AndroidRuntime(7277):     at java.io.ByteArrayOutputStream.writeTo(ByteArrayOutputStream.java:231)
08-27 11:46:39.694: E/AndroidRuntime(7277):     at com.elynx.pogoxmitm.MitmOutputStream.sendStoredData(MitmOutputStream.java:50)
08-27 11:46:39.694: E/AndroidRuntime(7277):     at com.elynx.pogoxmitm.MitmOutputStream.close(MitmOutputStream.java:22)
08-27 11:46:39.694: E/AndroidRuntime(7277):     at com.nianticlabs.nia.network.NiaNet.doSyncRequest(NiaNet.java:207)
08-27 11:46:39.694: E/AndroidRuntime(7277):     at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
08-27 11:46:39.694: E/AndroidRuntime(7277):     at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
08-27 11:46:39.694: E/AndroidRuntime(7277):     at com.nianticlabs.nia.network.NiaNet.doSyncRequest(<Xposed>)
08-27 11:46:39.694: E/AndroidRuntime(7277):     at com.nianticlabs.nia.network.NiaNet.access$000(NiaNet.java:23)
08-27 11:46:39.694: E/AndroidRuntime(7277):     at com.nianticlabs.nia.network.NiaNet$3.run(NiaNet.java:79)
08-27 11:46:39.694: E/AndroidRuntime(7277):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1115)
08-27 11:46:39.694: E/AndroidRuntime(7277):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:590)
08-27 11:46:39.694: E/AndroidRuntime(7277):     at java.lang.Thread.run(Thread.java:818)`

**Comment by ELynx** [comment]
Got it!
Had it sometimes, put always away from PC to get actual logs.
Will work upon it.

**Comment by ELynx** [comment]
Improved in release 1.3
